version: '3.6'

services:
  db:
    image: postgres:14.7-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  es:
    image: elasticsearch:7.17.9
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  pgdata:
  esdata:
    driver: local